version: '3'


services:
    redis:
        image: redis:alpine
        volumes:
            - ./redis.conf:/usr/local/etc/redis/redis.conf
        ports:
            - '6379:6379'
        command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
        env_file:
            - '.env'

    postgres_db:
        image: 'postgres'
        environment:
            - POSTGRES_USER=${POSTGRES_DB_USER}
            - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB_NAME}
        ports:
            - '5432:5432'
        env_file:
            - '.env'

    web:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/core
            - ./static/:/static
            - ./media/:/media
        depends_on:
            - postgres_db
            - redis
        ports:
            - "8001:8001"
        entrypoint: [ "/core/entrypoint.sh" ]
        env_file:
            - '.env'

    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile_dev
        volumes:
            - ./static/:/static
            - ./media/:/media
        depends_on: 
            - web
            - postgres_db
        ports:
            - '80:80'
        env_file:
            - '.env'

    celery:
        build:
            context: ./
        command: celery -A core worker -l info
        volumes:
            - ./:/core
        environment:
            - DEBUG=0
            - SECRET_KEY=${DJANGO_SECRET_KEY}
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://:${REDIS_PASSWORD}@redis:6379/0
            - CELERY_BACKEND=redis://:${REDIS_PASSWORD}@redis:6379/0
        depends_on:
            - web
            - redis
        env_file:
            - '.env'

    celery-beat:
        build:
            context: ./
        command: celery -A core beat -l info
        volumes:
            - ./:/core
        environment:
            - DEBUG=0
            - SECRET_KEY=${DJANGO_SECRET_KEY}
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://:${REDIS_PASSWORD}@redis:6379/0
            - CELERY_BACKEND=redis://:${REDIS_PASSWORD}@redis:6379/0
        depends_on:
            - web
            - redis
        env_file:
            - '.env'